version: "3.9"
services:
  db:
    image: postgres:16
    container_name: copa_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/05.DDL.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./sql/06.DML.sql:/docker-entrypoint-initdb.d/02-dml.sql

volumes:
  pgdata:
